### ISSUE TITLE
parallel builds

### ISSUE THREAD

**Issue by rickysarraf** [Juniper/contrail-vnc#20]
Hi GUys,

I couldn't find another place, thus am asking here. 

Does the contrail build support parallel builds ?
My intent is to speeded up the build by utilizing all the cores on the box. But when I run make in parallel, the build fails.

Is it supported ?

**Comment by klash** [comment]
I have been working on parallel builds for contrail. It is almost ready to roll out. Should be doing this sometime this week or early next.

**Comment by rickysarraf** [comment]
On 02/17/2015 09:07 PM, Karl Klashinsky wrote:
> I have been working on parallel builds for contrail. It is almost
> ready to roll out. Should be doing this sometime this week or early next.
Thanks Karl.

It is good to know that. Can we reopen the bug, and close once you push
the changes ?

Also, is it okay to open further bugs here?
I'm currently working on repetitive builds for Contrail and may have
more issues to report.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by klash** [comment]
Sorry for the delay in response.

Although it would be fine to re-open the bug here, the relevant github repo
is actually contrail-build:
https://github.com/Juniper/contrail-build

Probably better to open a bug against that repo rather than this one.

However, if it's easier for you to follow/track against contrail-vnc, we can do that as well.
Let me know which you prefer.
